-- StarBase Database Initialization
-- SQLite 3

CREATE TABLE IF NOT EXISTS system_config (
    key VARCHAR PRIMARY KEY,
    value VARCHAR
);

CREATE TABLE IF NOT EXISTS admin_users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR UNIQUE,
    password_hash VARCHAR
);

CREATE TABLE IF NOT EXISTS approved_apps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR,
    url VARCHAR,
    description TEXT,
    developer VARCHAR,
    deploy_env VARCHAR,
    category VARCHAR,
    scope VARCHAR,
    admin_contact VARCHAR,
    thumbnail BLOB,
    status SMALLINT DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pending_apps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR,
    url VARCHAR,
    description TEXT,
    developer VARCHAR,
    deploy_env VARCHAR,
    category VARCHAR,
    scope VARCHAR,
    admin_contact VARCHAR,
    thumbnail BLOB,
    submit_token VARCHAR UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user VARCHAR,
    action VARCHAR,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Default Config
INSERT OR IGNORE INTO system_config (key, value) VALUES ('title', '办公网网信系统融合应用平台');
INSERT OR IGNORE INTO system_config (key, value) VALUES ('slogan', '打造网信系统开发、发布、推广应用的开放平台');

-- Default Admin (password: admin123)
-- Hash generated by bcrypt
INSERT OR IGNORE INTO admin_users (username, password_hash) VALUES ('admin', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWrn96pzvPNP.jgG.5v1.8v1.8v1.8'); 

-- Example Data
INSERT INTO approved_apps (name, url, description, developer, deploy_env, category, scope, admin_contact, status) VALUES 
('协同办公系统', 'http://oa.internal', '提供日常办公协同、文档管理、流程审批等核心功能', '信息中心', '生产环境', 'web', '全公司', '张三', 1),
('项目管理平台', 'http://pm.internal', '航天项目全生命周期管理，支持任务分配、进度跟踪、资源调度', '研发部', '生产环境', 'web', '研发部', '李四', 1),
('数据资源中心', 'http://data.internal', '统一数据资源管理，提供数据查询、分析和可视化服务', '数据部', '生产环境', 'data', '数据部', '王五', 1),
('代码仓库平台', 'http://gitlab.internal', 'Git代码托管、版本管理、代码审查和CI/CD集成', '技术部', '生产环境', 'service', '技术部', '赵六', 1),
('系统监控中心', 'http://monitor.internal', '实时监控系统运行状态、性能指标和告警信息', '运维部', '生产环境', 'service', '运维部', '孙七', 1),
('知识库系统', 'http://wiki.internal', '技术文档、规范标准、最佳实践的集中管理和分享', '技术委员会', '测试环境', 'other', '技术委员会', '周八', 1);
